package values

var Pokemons []Pokemon = []Pokemon{
	{
		nom:           "Bulbizarre",
		classe:        "plante",
		description:   "Une plante puissante et résistante",
		vie:           60,
		maxVie:        60,
		chanceCapture: 90,
		attaques: []Attaque{{
			nom:         "Fouetard",
			description: "Fouete l'adversaire avec une liane",
			classe:      "plante",
			degatMin:    10,
			degatMax:    30,
			prixVie:     0,
		}},
	},
	{
		nom:           "Salamèche",
		classe:        "Feu",
		description:   "Un Pokémon de feu fougueux et déterminé",
		vie:           60,
		maxVie:        60,
		chanceCapture: 90,
		attaques: []Attaque{{
			nom:         "Boule de feu",
			description: "Envoie une boule de feu sur l'adversaire",
			classe:      "feu",
			degatMin:    10,
			degatMax:    30,
			prixVie:     0,
		}},
	},
	{
		nom:           "Carapuce",
		classe:        "eau",
		description:   "Un Pokémon d'eau calme et réfléchi",
		vie:           60,
		maxVie:        60,
		chanceCapture: 90,
		attaques: []Attaque{{
			nom:         "Jet d'eau",
			description: "Arrose d'un jet puissant l'adversaire",
			classe:      "eau",
			degatMin:    10,
			degatMax:    30,
			prixVie:     0,
		}},
	},
	{
		nom:           "Pikachu",
		classe:        "Électrique",
		description:   "Un Pokémon électrique mignon mais puissant",
		vie:           55,
		maxVie:        55,
		chanceCapture: 90,
		attaques: []Attaque{
			{
				nom:         "Éclair",
				description: "Lance une décharge électrique sur l'adversaire",
				classe:      "Électrique",
				degatMin:    15,
				degatMax:    35,
				prixVie:     0,
			},
		},
	},
	{
		nom:           "Rondoudou",
		classe:        "Normal",
		description:   "Un Pokémon rond et mignon qui aime chanter",
		vie:           80,
		maxVie:        80,
		chanceCapture: 90,
		attaques: []Attaque{
			{
				nom:         "Mélodie",
				description: "Chante une mélodie apaisante",
				classe:      "Normal",
				degatMin:    0,
				degatMax:    0,
				prixVie:     -10,
			},
		},
	},
	{
		nom:           "Dracaufeu",
		classe:        "Feu",
		description:   "Un dragon de feu impressionnant",
		vie:           80,
		maxVie:        80,
		chanceCapture: 80,
		attaques: []Attaque{
			{
				nom:         "Déflagration",
				description: "Déclenche une déflagration de feu intense",
				classe:      "Feu",
				degatMin:    20,
				degatMax:    40,
				prixVie:     0,
			},
		},
	},
	{
		nom:           "Léviator",
		classe:        "Eau",
		description:   "Un puissant Pokémon eau avec une peau dure",
		vie:           90,
		maxVie:        90,
		chanceCapture: 70,
		attaques: []Attaque{
			{
				nom:         "Hydrocanon",
				description: "Déchaîne un puissant jet d'eau sur l'adversaire",
				classe:      "Eau",
				degatMin:    25,
				degatMax:    45,
				prixVie:     0,
			},
		},
	},
	{
		nom:           "Ptera",
		classe:        "Vol",
		description:   "Un Pokémon volant préhistorique",
		vie:           70,
		maxVie:        70,
		chanceCapture: 80,
		attaques: []Attaque{
			{
				nom:         "Rafale de vent",
				description: "Crée une rafale de vent tranchante",
				classe:      "Vol",
				degatMin:    15,
				degatMax:    35,
				prixVie:     0,
			},
		},
	},
	{
		nom:           "Goupix",
		classe:        "Feu",
		description:   "Un Pokémon renard de feu aux neuf queues",
		vie:           70,
		maxVie:        70,
		chanceCapture: 85,
		attaques: []Attaque{
			{
				nom:         "Brasier",
				description: "Embrase l'adversaire avec des flammes intenses",
				classe:      "Feu",
				degatMin:    15,
				degatMax:    30,
				prixVie:     0,
			},
		},
	},
	{
		nom:           "Gyrados",
		classe:        "Eau",
		description:   "Un Pokémon eau féroce et redoutable",
		vie:           85,
		maxVie:        85,
		chanceCapture: 75,
		attaques: []Attaque{
			{
				nom:         "Ouragan",
				description: "Crée un ouragan dévastateur",
				classe:      "Eau",
				degatMin:    20,
				degatMax:    40,
				prixVie:     0,
			},
		},
	},
	{
		nom:           "Mewtwo",
		classe:        "Psychique",
		description:   "Un Pokémon psychique légendaire avec un pouvoir mental immense",
		vie:           100,
		maxVie:        100,
		chanceCapture: 50,
		attaques: []Attaque{
			{
				nom:         "Psycho Explosion",
				description: "Libère une explosion psychique",
				classe:      "Psychique",
				degatMin:    30,
				degatMax:    60,
				prixVie:     0,
			},
		},
	},
	{
		nom:           "Ronflex",
		classe:        "Normal",
		description:   "Un Pokémon paresseux mais incroyablement résistant",
		vie:           120,
		maxVie:        120,
		chanceCapture: 60,
		attaques: []Attaque{
			{
				nom:         "Écrasement",
				description: "Écrase l'adversaire avec son énorme masse",
				classe:      "Normal",
				degatMin:    40,
				degatMax:    80,
				prixVie:     0,
			},
		},
	},
}
